#!/usr/bin/env bash
# Back up and restore Arch Linux config files tracked in dotfiles.conf.
set -euo pipefail

# shellcheck source=lib/common.sh
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/common.sh"

TIMER_NAME="dotfiles-backup"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

usage() {
    cat <<USAGE
Usage: ${0##*/} <command> [options] [paths...]

Commands:
  backup [paths]      Copy tracked configs from the system into this repo and
                      snapshot the installed package lists.
  restore [paths]     Copy configs from this repo back onto the system. Files that
                      get overwritten are saved under $STATE_DIR/backups/.
  status [paths]      Show which tracked paths differ from the repo copy.
  diff [paths]        Show a unified diff between the repo copy and the system.
  add <path> [pkgs]   Start tracking a path (and the packages it needs), then back it up.
  list                List tracked paths and their packages.
  packages            Only snapshot installed packages into packages/.
  timer <enable|disable|status> [--calendar SPEC] [--no-push]
                      Manage a systemd user timer that runs 'backup --push'.

Options:
  -c, --commit        (backup) Commit changes to git afterwards.
  -p, --push          (backup) Push after committing (implies --commit).
  -y, --yes           (restore) Do not ask for confirmation.
  -n, --dry-run       Show what would happen without changing anything.
  -q, --quiet         Only print warnings and errors.
  -h, --help          Show this help.

Paths are given exactly as written in dotfiles.conf (e.g. .config/nvim).
USAGE
}

# ---------------------------------------------------------------------------
# helpers

rsync_excludes() {
    if [[ -f $EXCLUDE_FILE ]]; then printf '%s\n' "--exclude-from=$EXCLUDE_FILE"; fi
}

# Resolve the paths to operate on: explicit args (validated) or all tracked paths.
select_paths() {
    local -a tracked
    mapfile -t tracked < <(conf_paths)
    if (( $# == 0 )); then
        printf '%s\n' "${tracked[@]}"
        return
    fi
    local p t found
    for p in "$@"; do
        p="${p#\~/}"; p="${p%/}"
        found=0
        for t in "${tracked[@]}"; do [[ $t == "$p" ]] && found=1 && break; done
        (( found )) || die "'$p' is not tracked in $(basename "$CONF_FILE") (use: ${0##*/} add $p)"
        printf '%s\n' "$p"
    done
}

# ---------------------------------------------------------------------------
# backup

backup_path() {
    local path="$1" src dst
    src="$(live_path "$path")"
    dst="$(store_path "$path")"
    local -a excl
    mapfile -t excl < <(rsync_excludes)

    if [[ ! -e $src ]]; then
        warn "skipping $path: not found on this system"
        return 0
    fi
    if [[ ! -r $src ]]; then
        warn "skipping $path: not readable by $(id -un)"
        return 0
    fi

    run mkdir -p "$(dirname "$dst")"
    if [[ -d $src ]]; then
        run rsync -a --checksum --delete --delete-excluded "${excl[@]}" "$src/" "$dst/"
    else
        run rsync -a --checksum "$src" "$dst"
    fi
    info "backed up $path"
}

snapshot_packages() {
    if ! command -v pacman >/dev/null 2>&1; then
        warn "pacman not found; skipping package snapshot"
        return 0
    fi
    if (( DRY_RUN )); then
        run "pacman -Qqen > packages/pacman.txt"
        run "pacman -Qqem > packages/aur.txt"
        return 0
    fi
    mkdir -p "$PKG_DIR"
    { echo "# Explicitly installed repo packages (generated by dotfiles.sh, do not edit)"
      pacman -Qqen; } >"$PKG_DIR/pacman.txt"
    { echo "# Explicitly installed foreign/AUR packages (generated by dotfiles.sh, do not edit)"
      pacman -Qqem || true; } >"$PKG_DIR/aur.txt"
    info "package lists saved to packages/"
}

# Refuse to commit anything that looks like a private key.
check_secrets() {
    local -a hits=()
    local dir
    for dir in "$HOME_STORE" "$ROOT_STORE"; do
        [[ -d $dir ]] || continue
        mapfile -t -O "${#hits[@]}" hits < <(grep -rlE -- '-----BEGIN ([A-Z]+ )?PRIVATE KEY-----' "$dir" 2>/dev/null || true)
    done
    if (( ${#hits[@]} )); then
        error "refusing to commit: private keys found in:"
        printf '  %s\n' "${hits[@]#"$REPO_DIR/"}" >&2
        error "remove them and add a pattern to exclude.conf"
        return 1
    fi
}

git_commit() {
    local push="$1"
    git -C "$REPO_DIR" rev-parse --git-dir >/dev/null 2>&1 || die "$REPO_DIR is not a git repository"
    check_secrets
    local -a items=()
    local item
    for item in home root packages dotfiles.conf exclude.conf services.conf; do
        [[ -e $REPO_DIR/$item ]] && items+=("$item")
    done
    run git -C "$REPO_DIR" add -A -- "${items[@]}"
    if (( ! DRY_RUN )) && git -C "$REPO_DIR" diff --cached --quiet; then
        info "no changes to commit"
    else
        run git -C "$REPO_DIR" commit -q -m "backup: $(uname -n) $(date '+%Y-%m-%d %H:%M')"
        ok "committed changes"
    fi
    if [[ $push == 1 ]]; then
        if git -C "$REPO_DIR" rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
            run git -C "$REPO_DIR" push -q
        else
            local branch
            branch="$(git -C "$REPO_DIR" symbolic-ref --short HEAD)"
            run git -C "$REPO_DIR" push -q -u origin "$branch"
        fi
        ok "pushed to remote"
    fi
}

cmd_backup() {
    local commit=0 push=0
    local -a args=()
    while (( $# )); do
        case $1 in
            -c|--commit)  commit=1 ;;
            -p|--push)    commit=1; push=1 ;;
            -n|--dry-run) DRY_RUN=1 ;;
            -q|--quiet)   QUIET=1 ;;
            -*) die "unknown option for backup: $1" ;;
            *)  args+=("$1") ;;
        esac
        shift
    done
    need_cmd rsync rsync

    local -a paths
    mapfile -t paths < <(select_paths "${args[@]}")
    local p
    for p in "${paths[@]}"; do backup_path "$p"; done
    snapshot_packages
    ok "backup complete (${#paths[@]} paths)"
    if (( commit )); then git_commit "$push"; fi
}

# ---------------------------------------------------------------------------
# restore

restore_path() {
    local path="$1" snapshot="$2" src dst
    local -a sudo=()
    src="$(store_path "$path")"
    dst="$(live_path "$path")"
    local -a excl
    mapfile -t excl < <(rsync_excludes)

    if [[ ! -e $src ]]; then
        warn "skipping $path: no copy in repo (run backup first)"
        return 0
    fi

    # --backup moves every file rsync would overwrite into the snapshot dir first.
    local -a opts=(-a --checksum --backup)
    if is_system_path "$path"; then
        sudo=(sudo)
        # Repo files are owned by the user; system files should end up owned by root.
        opts+=(--no-owner --no-group)
    fi

    if [[ -d $src ]]; then
        run "${sudo[@]}" mkdir -p "$dst"
        run "${sudo[@]}" rsync "${opts[@]}" --backup-dir="$snapshot/${path#/}" "${excl[@]}" "$src/" "$dst/"
    else
        run "${sudo[@]}" mkdir -p "$(dirname "$dst")"
        run "${sudo[@]}" rsync "${opts[@]}" --backup-dir="$snapshot/$(dirname "${path#/}")" "$src" "$dst"
    fi
    info "restored $path"
}

cmd_restore() {
    local yes=0
    local -a args=()
    while (( $# )); do
        case $1 in
            -y|--yes)     yes=1 ;;
            -n|--dry-run) DRY_RUN=1 ;;
            -q|--quiet)   QUIET=1 ;;
            -*) die "unknown option for restore: $1" ;;
            *)  args+=("$1") ;;
        esac
        shift
    done
    need_cmd rsync rsync

    local -a paths
    mapfile -t paths < <(select_paths "${args[@]}")
    if (( ! yes && ! DRY_RUN )); then
        printf 'This will overwrite these paths with the repo copies:\n'
        printf '  %s\n' "${paths[@]}"
        confirm "Continue?" || die "aborted"
    fi

    local snapshot
    snapshot="$STATE_DIR/backups/$(date +%Y%m%d-%H%M%S)"
    local p
    for p in "${paths[@]}"; do restore_path "$p" "$snapshot"; done
    ok "restore complete"
    if [[ -d $snapshot ]]; then
        ok "overwritten files were saved to $snapshot"
    fi
}

# ---------------------------------------------------------------------------
# status / diff / list / add

status_line() { printf '  %s%-10s%s %s\n' "$1" "$2" "$C_RESET" "$3"; }

cmd_status() {
    need_cmd rsync rsync
    local -a paths excl
    mapfile -t paths < <(select_paths "$@")
    mapfile -t excl < <(rsync_excludes)
    local p src dst changes clean=1
    for p in "${paths[@]}"; do
        src="$(live_path "$p")"
        dst="$(store_path "$p")"
        if [[ ! -e $src && ! -e $dst ]]; then
            status_line "$C_RED" missing "$p"; clean=0; continue
        elif [[ ! -e $src ]]; then
            status_line "$C_YELLOW" not-local "$p"; clean=0; continue
        elif [[ ! -e $dst ]]; then
            status_line "$C_YELLOW" new "$p"; clean=0; continue
        fi
        if [[ -d $src ]]; then
            changes="$(rsync -a --checksum --dry-run --delete --itemize-changes "${excl[@]}" "$src/" "$dst/" 2>/dev/null \
                       | grep -Ev '^\.d|^cd' || true)"
        else
            changes="$(rsync -a --checksum --dry-run --itemize-changes "$src" "$dst" 2>/dev/null || true)"
        fi
        if [[ -n $changes ]]; then
            status_line "$C_YELLOW" modified "$p"
            clean=0
            if (( ! QUIET )); then
                sed -E 's/^\*deleting +/      - /; s/^>f\+{9} /      + /; s/^[>.][^ ]* /      ~ /' <<<"$changes"
            fi
        else
            status_line "$C_GREEN" ok "$p"
        fi
    done
    if (( clean )); then
        ok "everything is in sync"
    else
        info "'${0##*/} backup' saves local changes (+ new, ~ changed, - removed locally); 'restore' discards them"
    fi
}

cmd_diff() {
    local -a paths
    mapfile -t paths < <(select_paths "$@")
    local -a dx=()
    local pat
    while IFS= read -r pat; do dx+=(-x "${pat%/}"); done < <(list_file "$EXCLUDE_FILE")
    local p
    for p in "${paths[@]}"; do
        diff -ruN --color=auto "${dx[@]}" "$(store_path "$p")" "$(live_path "$p")" || true
    done
}

cmd_list() {
    [[ -f $CONF_FILE ]] || die "config file not found: $CONF_FILE"
    local line path pkgs
    while IFS= read -r line || [[ -n $line ]]; do
        line="$(_clean_line "$line")"
        [[ -z $line ]] && continue
        read -r path pkgs <<<"$line"
        printf '%s%-40s%s %s\n' "$C_BOLD" "$path" "$C_RESET" "${pkgs:--}"
    done <"$CONF_FILE"
}

cmd_add() {
    (( $# )) || die "usage: ${0##*/} add <path> [packages...]"
    local path="$1"; shift
    # Normalise to a $HOME-relative path where possible.
    path="${path#\~/}"
    if [[ $path != /* && -e $path ]]; then
        path="$(readlink -f "$path")"
    fi
    [[ $path == "$HOME"/* ]] && path="${path#"$HOME"/}"
    path="${path%/}"
    [[ -e $(live_path "$path") ]] || die "$(live_path "$path") does not exist"

    if conf_paths | grep -qxF -- "$path"; then
        info "$path is already tracked"
    else
        printf '%-40s %s\n' "$path" "$*" >>"$CONF_FILE"
        ok "now tracking $path${*:+ (packages: $*)}"
    fi
    need_cmd rsync rsync
    backup_path "$path"
}

# ---------------------------------------------------------------------------
# systemd timer

cmd_timer() {
    local action="${1:-status}"
    (( $# )) && shift
    local calendar="daily" push=1
    while (( $# )); do
        case $1 in
            --calendar) calendar="${2:?--calendar needs a value}"; shift ;;
            --no-push)  push=0 ;;
            *) die "unknown option for timer: $1" ;;
        esac
        shift
    done
    need_cmd systemctl systemd

    case $action in
        enable)
            local flags="--commit --quiet"
            (( push )) && flags="--push --quiet"
            mkdir -p "$UNIT_DIR"
            cat >"$UNIT_DIR/$TIMER_NAME.service" <<UNIT
[Unit]
Description=Back up dotfiles into $REPO_DIR
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/bin/env bash "$REPO_DIR/dotfiles.sh" backup $flags
UNIT
            cat >"$UNIT_DIR/$TIMER_NAME.timer" <<UNIT
[Unit]
Description=Periodic dotfiles backup

[Timer]
OnCalendar=$calendar
Persistent=true
RandomizedDelaySec=10min

[Install]
WantedBy=timers.target
UNIT
            systemctl --user daemon-reload
            systemctl --user enable --now "$TIMER_NAME.timer"
            ok "timer enabled ($calendar); logs: journalctl --user -u $TIMER_NAME.service"
            ;;
        disable)
            systemctl --user disable --now "$TIMER_NAME.timer" 2>/dev/null || true
            rm -f "${UNIT_DIR:?}/${TIMER_NAME:?}.service" "${UNIT_DIR:?}/${TIMER_NAME:?}.timer"
            systemctl --user daemon-reload
            ok "timer disabled"
            ;;
        status)
            systemctl --user list-timers "$TIMER_NAME.timer" --all --no-pager || true
            ;;
        *) die "usage: ${0##*/} timer <enable|disable|status>" ;;
    esac
}

# ---------------------------------------------------------------------------

main() {
    local cmd="${1:-}"
    (( $# )) && shift
    case $cmd in
        backup)   cmd_backup "$@" ;;
        restore)  cmd_restore "$@" ;;
        status)   cmd_status "$@" ;;
        diff)     cmd_diff "$@" ;;
        list|ls)  cmd_list ;;
        add)      cmd_add "$@" ;;
        packages) snapshot_packages ;;
        timer)    cmd_timer "$@" ;;
        -h|--help|help|'') usage ;;
        *) usage >&2; die "unknown command: $cmd" ;;
    esac
}

main "$@"
